### ISSUE TITLE
Possible to get old versions of plugin?

### ISSUE THREAD

**Issue by ludakhris** [KabaLabs/Cypress-Recorder#138]
All,

I've been searching the web for a way to do this but is there any way to get the 1.0.0 version of the plugin?

**Comment by abbeycampbell** [comment]
Hey! 
I've added two releases. Now you can just checkout to the [1.0.0 branch](https://github.com/KabaLabs/Cypress-Recorder/tree/1.0.0) and run it locally on your machine.

**Comment by ludakhris** [comment]
Well I meant the actual .crz files (aka the chrome extension itself).

**Comment by abbeycampbell** [comment]
@ludakhris did you try running the script `npm run rebuild` and then loading unpacked extensions in chrome? 
Also, can I ask why you need the older version of the extension? The only difference between version 1.0.0 and the current release on the Chrome web store is a minor bug fix that has to do with copying to the clipboard, I believe.

**Comment by ludakhris** [comment]
@abbeycampbell I didn't know or think of doing that so yes I will do that. Sorry not super familiar with chrome extensions. 

Happy to answer the "why", I have a customer who utilitizes Chrome 57 on some closed networks. And the copy to clipboard doesn't work with the newer version of the plug-in
