### ISSUE TITLE
Recognizing data tags

### ISSUE THREAD

**Issue by WannesDC** [KabaLabs/Cypress-Recorder#148]
hello

Not entirely sure where to post this, but I'm running into an issue where I can't seem to use this in my project, as the navigation's classes are mostly generic.

I've added a few data tags to be able to test this manually however it'd be pretty cool if there was a way for the extension to recognize this. 

Example html:
```
<div class="menu-login" data-cy="my-button">
<dev-extreme-wrapper>
<dev-extreme-button class="some-generic-class"></dev-extreme-button>
</dev-extreme-wrapper>
</div>
```
the test recorder is trying to do:

cy.get('.some-generic-class').click();

whereas I'd expect:

cy.get('[data-cy=my-button]')

I could change this manually of course, but I'm wondering whether it's possible to include the option for the extension to recognize any data-x tag when it is recording.

**Comment by aviyadeveloper** [comment]
Just adding some support to this. A setting that allows to give some priority to specific data tags would be great!

**Comment by kassuro** [comment]
Would love this feature as well, since it detects only the ids for us, but those are generated from the ui library we use, so I would need to rewrite most of the script to use the data tags instead :disappointed:

**Comment by adam-stover** [comment]
PR From @estruyf has added support for data-cy, data-test, and data-testid attributes. Will work on ability to customize!

**Comment by Fasani** [comment]
To understand this better.

Assuming I want to test a login. I could add ‘data-cy’ attributes to my login and password inputs as well as the submit button. 

And the recorder would use those elements via their data attr so I end up with generated code which would be more like below:
cy.get('[data-cy=username]')
cy.get('[data-cy=password]')
cy.get('[data-cy=button]')

Which would mean that if I refactor my code later on as long as I keep the data attributes my tests would quite likely not need to be refactored? Correct?

**Comment by Fasani** [comment]
Also the PR from @estruyf was merged or not yet?

**Comment by adam-stover** [comment]
@Fasani Correct! The PR from @estruyf has been merged and this version (1.0.5) is live on the Chrome Store.

**Comment by Fasani** [comment]
@adam-stover ty

**Comment by aviyadeveloper** [comment]
this is great!

**Comment by adam-stover** [comment]
Thanks for the requests. Thanks as well @estruyf for the implementation. Merged in https://github.com/KabaLabs/Cypress-Recorder/pull/150 and released in https://github.com/KabaLabs/Cypress-Recorder/releases/tag/v1.0.5
