### ISSUE TITLE
"Chrome Webstore: Error 404 (Not found)!!1" ?

### ISSUE THREAD

**Issue by tfrijsewijk** [KabaLabs/Cypress-Recorder#166]
Hi,

I wanted to give your plugin a go but the url in the readme.MD doesn't seem to work: https://chrome.google.com/webstore/detail/cypress-recorder/glcapdcacdfkokcmicllhcjigeodacab

**Comment by adam-stover** [comment]
Hi Thomas,

Thank you for alerting us to this issue. Without warning, Chrome removed
our extension. It appears their policies changes -- our extension will be
back, we just had to remove the `tabs` and `clipboardWrite` permissions as
we weren't using them.

In the meantime, if you clone the source you can build the extension and
load it onto your Chrome. There are also similar extensions to ours which
you can try out. I'm always happy to help if you have any questions.

Thank you again!
Adam

**Comment by rehrumesh** [comment]
I also got the same error. Thanks for the clarifications Adam. Hope it gets available in the store soon.

**Comment by adam-stover** [comment]
We are back! https://chrome.google.com/webstore/detail/cypress-recorder/glcapdcacdfkokcmicllhcjigeodacab
